# *** This Dockefile is generated by KloverCloud *** #
FROM php:7.4
RUN apt-get update -y && apt-get install -y openssl zip unzip git
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-install pdo
RUN useradd -ms /bin/bash klovercloud
WORKDIR /home/klovercloud
COPY --chown=klovercloud:klovercloud . .
RUN mkdir -p bootstrap/cache
RUN mkdir -p vendor
RUN composer install
USER klovercloud
CMD php artisan serve --host=0.0.0.0 --port=8080
EXPOSE 8080
